import pandas as pd
import joblib
from pathlib import Path

from feature_engineering import create_features


# Project paths
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_PATH = (
    BASE_DIR
    / "data"
    / "processed"
    / "airshift_feature_engineered.csv"
)

MODEL_PATH = (
    BASE_DIR
    / "models"
    / "xgboost_final.joblib"
)


# Load data
df = pd.read_csv(
    DATA_PATH,
    parse_dates=["datetime"]
)


# Keep only the original raw columns
RAW_COLUMNS = [
    "No",
    "year",
    "month",
    "day",
    "hour",
    "PM2.5",
    "PM10",
    "SO2",
    "NO2",
    "CO",
    "O3",
    "TEMP",
    "PRES",
    "DEWP",
    "RAIN",
    "wd",
    "WSPM",
    "station",
    "datetime",
]

df = df[RAW_COLUMNS]


# Select one station
station = df["station"].iloc[0]

station_data = (
    df[df["station"] == station]
    .sort_values("datetime")
    .copy()
)


# Select 7 consecutive hourly observations
sample = station_data.head(7).copy()


print("Sample shape:", sample.shape)
print("Station:", station)
print("Datetime range:")
print(
    sample["datetime"].min(),
    "→",
    sample["datetime"].max()
)


# Create engineered features
featured = create_features(sample)


print("\nEngineered shape:", featured.shape)


# Load final model
model = joblib.load(MODEL_PATH)

MODEL_FEATURES = list(
    model.feature_names_in_
)


# Check required model features
missing_features = [
    feature
    for feature in MODEL_FEATURES
    if feature not in featured.columns
]


# Features generated by the API
# that are not part of the model input
extra_features = [
    feature
    for feature in featured.columns
    if feature not in MODEL_FEATURES
    and feature not in ["No", "datetime"]
]


print(
    "\nMissing model features:",
    len(missing_features)
)

print(
    "Extra engineered features:",
    len(extra_features)
)


if missing_features:
    print("\nMissing features:")
    for feature in missing_features:
        print("-", feature)


if extra_features:
    print("\nExtra features:")
    for feature in extra_features:
        print("-", feature)


# Select the final observation
# This is the observation that has the
# maximum available history.
final_row = featured.iloc[-1][MODEL_FEATURES]


print(
    "\nFinal row shape:",
    final_row.shape
)

print(
    "Missing values in final row:",
    final_row.isna().sum()
)


# Check feature count
if len(MODEL_FEATURES) == 97:
    print("\nModel expects 97 features: OK")
else:
    print(
        "\nWARNING: Model expects",
        len(MODEL_FEATURES),
        "features"
    )


# Final validation
if not missing_features and not extra_features:
    print(
        "\nFeature names match the final model: OK"
    )
else:
    print(
        "\nFeature names do NOT match the final model."
    )


print("\nFeature engineering test completed.")